### ISSUE TITLE
Update Documentation for Loopback 4

### ISSUE THREAD

**Issue by xzessmedia** [strongloop/loopback-connector-informix#56] opened 2019-09-26 14:41 UTC
Hi,
please update the documentation for using this connector with Loopback4.

We tried to use the datasource generator `lb4 datasource` after installing this repository via npm but it is not listed.
We tried to add it with "other" datasource but this failed too.
There should be enough documentation to answer people's questions to use this with Loopback4.
Currently there is no documentation either on google or youtube and the provided steps available in Readme.MD of this repository is not up to date!

I'm looking really forward for any help towards Loopback4 and this Informix Connector.

Is there anybody using this connector with Loopback4 ?
We really want to use Loopback for our projects but currently loopback seems to not be production ready especially using it with an informix database? Correct me if im wrong!

**Comment by dhmlau** [comment] 2019-09-27 22:09
@raymondfeng @bajtos, do you know why the informix connector is not part of the tooling?  Is it just a matter of updating https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json? Thanks.

**Comment by xzessmedia** [comment] 2019-10-26 13:07
hi, any news on this? is nobody using informix with loopback?

**Comment by bajtos** [comment] 2020-01-06 10:45
> do you know why the informix connector is not part of the tooling? Is it just a matter of updating https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json? Thanks.

IDK, to be honest. I think we should first verify that the connector works with LB4 and update the README if needed. Then we can add the connector to the list of connectors offered by `lb4 datasource`.

Let's treat this issue as a duplicate of https://github.com/strongloop/loopback-next/issues/4368

**Comment by dhmlau** [comment] 2020-02-09 02:45
Closing as duplicate strongloop/loopback-next#4368

**Closed as completed by dhmlau** 2020-02-09 02:45 UTC
Labels: doc
